# Everything produced by workflow will be stored here, including raw data
output_dir: /path/to/

# Directory containing local pdb (.cif.gz files) with new pdb format
pdb_dir: /path/to/pdb

# Path to the Chemical Component Dictionary (.cif.gz)
ccd: /path/to/ccd

# Path to data.csv from https://valtrendsdb.biodata.ceitec.cz/download.php
valtrends_file: /path/to/data